"""JevFish runtime adapter for OASIS simulations.

JevFish keeps the upstream OASIS simulation code intact and wraps environments
at runtime. In ``llm`` mode it is an exact OASIS ``LLMAction`` baseline. In
``hybrid`` mode Jev acts as a fast System-One policy: one Jev call predicts a
sparse bundle of social actions and independent targets, cheap actions execute
as OASIS ``ManualAction`` objects, and language is generated by System Two only
for actions that actually need text. ``single`` policy mode preserves the V0.1
one-action router for compatibility and ablations.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import sqlite3
from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import Any, Dict, Mapping, Optional


DEFAULT_MODE = "hybrid"
DEFAULT_POLICY_MODE = "multi"


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _json_safe(value: Any, *, depth: int = 0) -> Any:
    """Convert arbitrary profile/config objects to a compact JSON-safe value."""
    if depth > 4:
        return str(value)
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if is_dataclass(value):
        return _json_safe(asdict(value), depth=depth + 1)
    if isinstance(value, Mapping):
        return {
            str(k): _json_safe(v, depth=depth + 1)
            for k, v in list(value.items())[:40]
        }
    if isinstance(value, (list, tuple, set)):
        return [_json_safe(v, depth=depth + 1) for v in list(value)[:40]]
    if hasattr(value, "model_dump"):
        try:
            return _json_safe(value.model_dump(), depth=depth + 1)
        except Exception:
            pass
    if hasattr(value, "__dict__"):
        try:
            public = {
                k: v for k, v in vars(value).items() if not k.startswith("_")
            }
            return _json_safe(public, depth=depth + 1)
        except Exception:
            pass
    return str(value)


def _platform_name(platform: Any) -> str:
    raw = getattr(platform, "value", platform)
    text = str(raw).lower()
    if "reddit" in text:
        return "reddit"
    return "twitter"


def _agent_id(agent: Any) -> int:
    for name in ("agent_id", "id"):
        value = getattr(agent, name, None)
        if value is not None:
            try:
                return int(value)
            except (TypeError, ValueError):
                pass
    return -1


def _load_config_from_argv() -> Dict[str, Any]:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--config")
    args, _ = parser.parse_known_args()
    if not args.config:
        return {}
    try:
        with open(args.config, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        print(f"[JevFish] unable to load simulation config: {exc}")
        return {}


class JevDecisionEngine:
    """Turn high-frequency OASIS LLM actions into Jev-backed action bundles."""

    def __init__(self, legacy_module: Any, config: Dict[str, Any]) -> None:
        self.legacy = legacy_module
        self.config = config
        jevfish_config = (
            config.get("jevfish", {}) if isinstance(config.get("jevfish"), dict) else {}
        )

        configured_mode = str(jevfish_config.get("decision_engine", "")).strip().lower()
        self.mode = os.getenv(
            "JEVFISH_DECISION_ENGINE", configured_mode or DEFAULT_MODE
        ).strip().lower()
        if self.mode not in {"llm", "hybrid", "jev"}:
            print(
                f"[JevFish] unknown decision engine {self.mode!r}; "
                f"using {DEFAULT_MODE}"
            )
            self.mode = DEFAULT_MODE

        configured_policy = str(jevfish_config.get("policy_mode", "")).strip().lower()
        self.policy_mode = os.getenv(
            "JEVFISH_POLICY_MODE", configured_policy or DEFAULT_POLICY_MODE
        ).strip().lower()
        if self.policy_mode not in {"single", "multi"}:
            print(
                f"[JevFish] unknown policy mode {self.policy_mode!r}; "
                f"using {DEFAULT_POLICY_MODE}"
            )
            self.policy_mode = DEFAULT_POLICY_MODE

        self.threshold = float(os.getenv("JEVFISH_CONFIDENCE_THRESHOLD", "0.58"))
        self.max_posts = max(
            1,
            min(30, int(os.getenv("JEVFISH_MAX_CONTEXT_POSTS", "12"))),
        )
        self.max_actions = max(
            1,
            min(8, int(os.getenv("JEVFISH_MAX_ACTIONS_PER_AGENT", "3"))),
        )
        self.max_system_two_actions = max(
            0,
            min(3, int(os.getenv("JEVFISH_MAX_SYSTEM_TWO_ACTIONS", "1"))),
        )
        self.sample_probabilities = _env_bool(
            "JEVFISH_SAMPLE_PROBABILITIES", True
        )
        self.api_key = os.getenv("TYPESAFE_API_KEY", "").strip()
        self.model = (
            os.getenv("TYPESAFE_DEFAULT_MODEL", "jev-latest").strip()
            or "jev-latest"
        )

        self.llm_api_key = os.getenv("LLM_API_KEY", "").strip()
        self.llm_base_url = os.getenv("LLM_BASE_URL", "").strip() or None
        self.llm_model = os.getenv("LLM_MODEL_NAME", "").strip()

        self._client: Any = None
        self._llm_client: Any = None
        self._warned_missing_key = False
        self._warned_missing_llm = False
        self.stats: Dict[str, Any] = {
            "mode": self.mode,
            "policy_mode": self.policy_mode,
            "jev_calls": 0,
            "jev_plans": 0,
            "jev_manual_actions": 0,
            "multi_action_agents": 0,
            "llm_fallbacks": 0,
            "llm_escalations": 0,
            "system_two_calls": 0,
            "system_two_errors": 0,
            "generative_skipped": 0,
            "passthrough_actions": 0,
            "errors": 0,
            "uncertain_gates": 0,
            "manual_by_type": {},
            "system_two_by_type": {},
            "selected_by_type": {},
        }
        self._agent_configs = {
            int(item.get("agent_id", -1)): item
            for item in config.get("agent_configs", [])
            if isinstance(item, dict)
        }

    def _llm_action(self, *, escalated: bool = False) -> Any:
        self.stats["llm_fallbacks"] += 1
        if escalated:
            self.stats["llm_escalations"] += 1
        return self.legacy.LLMAction()

    def _record_selected(self, action_name: str) -> None:
        bucket = self.stats["selected_by_type"]
        bucket[action_name] = int(bucket.get(action_name, 0)) + 1

    def _manual_action(
        self,
        action_type: Any,
        action_args: Dict[str, Any],
    ) -> Any:
        name = getattr(action_type, "name", str(action_type))
        bucket = self.stats["manual_by_type"]
        bucket[name] = int(bucket.get(name, 0)) + 1
        self.stats["jev_manual_actions"] += 1
        return self.legacy.ManualAction(
            action_type=action_type,
            action_args=action_args,
        )

    async def _ensure_client(self) -> Optional[Any]:
        if self.mode == "llm":
            return None
        if not self.api_key:
            if self.mode == "jev":
                raise RuntimeError(
                    "JEVFISH_DECISION_ENGINE=jev requires TYPESAFE_API_KEY"
                )
            if not self._warned_missing_key:
                print(
                    "[JevFish] TYPESAFE_API_KEY missing; hybrid mode is "
                    "falling back to LLMAction"
                )
                self._warned_missing_key = True
            return None
        if self._client is None:
            from typesafe_sdk import AsyncTypeSafeClient

            self._client = AsyncTypeSafeClient(
                api_key=self.api_key,
                model=self.model,
            )
        return self._client

    async def _ensure_llm_client(self) -> Optional[Any]:
        if not self.llm_api_key or not self.llm_model:
            if not self._warned_missing_llm:
                print(
                    "[JevFish] LLM_API_KEY/LLM_MODEL_NAME missing; "
                    "language actions will use the OASIS LLM fallback"
                )
                self._warned_missing_llm = True
            return None
        if self._llm_client is None:
            from openai import AsyncOpenAI

            self._llm_client = AsyncOpenAI(
                api_key=self.llm_api_key,
                base_url=self.llm_base_url,
            )
        return self._llm_client

    def _persona(self, agent: Any) -> Any:
        aid = _agent_id(agent)
        configured = self._agent_configs.get(aid)
        if configured:
            return _json_safe(configured)
        return _json_safe(
            getattr(agent, "user_info", {"agent_id": aid})
        )

    def _recent_posts(
        self,
        db_path: str,
        aid: int,
    ) -> list[dict[str, Any]]:
        if not db_path or not os.path.exists(db_path):
            return []
        try:
            connection = sqlite3.connect(db_path)
            cursor = connection.cursor()
            cursor.execute(
                """
                SELECT p.post_id, p.content, p.user_id,
                       u.agent_id, u.name, u.user_name
                FROM post p
                LEFT JOIN user u ON p.user_id = u.user_id
                ORDER BY p.post_id DESC
                LIMIT ?
                """,
                (self.max_posts * 2,),
            )
            rows = cursor.fetchall()
            connection.close()
        except Exception:
            return []

        posts: list[dict[str, Any]] = []
        for (
            post_id,
            content,
            user_id,
            author_agent_id,
            name,
            user_name,
        ) in rows:
            if (
                author_agent_id is not None
                and int(author_agent_id) == aid
            ):
                continue
            posts.append(
                {
                    "key": f"post_{int(post_id)}",
                    "post_id": int(post_id),
                    "content": (content or "")[:800],
                    "author_user_id": (
                        int(user_id) if user_id is not None else None
                    ),
                    "author_agent_id": (
                        int(author_agent_id)
                        if author_agent_id is not None
                        else None
                    ),
                    "author": (
                        name
                        or user_name
                        or f"user_{user_id}"
                    ),
                }
            )
            if len(posts) >= self.max_posts:
                break
        return posts

    @staticmethod
    def _sample_choice(
        answer: Any,
        *,
        stochastic: bool,
    ) -> str:
        if not stochastic:
            return str(answer.choice)
        probabilities = getattr(answer, "probabilities", None) or {}
        labels = list(probabilities.keys())
        weights = [
            max(0.0, float(probabilities[label]))
            for label in labels
        ]
        if labels and sum(weights) > 0:
            return str(
                random.choices(
                    labels,
                    weights=weights,
                    k=1,
                )[0]
            )
        return str(answer.choice)

    @staticmethod
    def _choice_confidence(
        answer: Any,
        selected: str,
    ) -> float:
        probabilities = getattr(answer, "probabilities", None) or {}
        if selected in probabilities:
            try:
                return float(probabilities[selected])
            except (TypeError, ValueError):
                pass
        try:
            return float(answer.confidence)
        except (TypeError, ValueError, AttributeError):
            return 0.0

    def _choose(
        self,
        answer: Any,
    ) -> tuple[str, float]:
        selected = self._sample_choice(
            answer,
            stochastic=self.sample_probabilities,
        )
        return selected, self._choice_confidence(answer, selected)

    def _target_from_answer(
        self,
        answer: Any,
        posts: list[dict[str, Any]],
    ) -> tuple[Optional[dict[str, Any]], float]:
        selected, confidence = self._choose(answer)
        target = next(
            (post for post in posts if post["key"] == selected),
            None,
        )
        return target, confidence

    def _state(
        self,
        agent: Any,
        platform: str,
        posts: list[dict[str, Any]],
    ) -> Dict[str, Any]:
        return {
            "platform": platform,
            "persona": self._persona(agent),
            "recent_feed": [
                {
                    "key": post["key"],
                    "author": post["author"],
                    "content": post["content"],
                }
                for post in posts
            ],
            "instruction": (
                "Act as this simulated person's fast intuitive behavior. "
                "Be sparse and realistic: most possible actions should be "
                "rejected. A normal person often does nothing and rarely "
                "performs more than a few actions in one tick. Do not "
                "optimize for engagement; preserve the persona."
            ),
        }

    @staticmethod
    def _binary_choice(
        Choice: Any,
        *,
        instruction: str,
        yes: str,
        no: str,
    ) -> Any:
        return Choice(
            instructions=instruction,
            criteria={
                "yes": yes,
                "no": no,
            },
        )

    @staticmethod
    def _target_choice(
        Choice: Any,
        *,
        instruction: str,
        posts: list[dict[str, Any]],
    ) -> Any:
        criteria = {
            post["key"]: {
                "author": post["author"],
                "content": post["content"],
            }
            for post in posts
        }
        criteria["none"] = "No feed post is a natural target."
        return Choice(
            instructions=instruction,
            criteria=criteria,
        )

    async def decide(
        self,
        agent: Any,
        *,
        db_path: str,
        platform: str,
    ) -> Any:
        """V0.1 single-action policy, kept for compatibility and ablations."""
        if self.mode == "llm":
            return self._llm_action()

        client = await self._ensure_client()
        if client is None:
            return self._llm_action()

        aid = _agent_id(agent)
        posts = self._recent_posts(db_path, aid)
        if not posts:
            return self._llm_action()

        action_criteria = {
            "do_nothing": (
                "Ignore the current feed and take no social action."
            ),
            "like_post": (
                "Like one existing post that this persona would "
                "positively react to."
            ),
            "follow_author": (
                "Follow the author of one existing post when the "
                "persona would want more from them."
            ),
            "generate": (
                "The persona should create original language: make a "
                "post, reply, quote, search, or otherwise do something "
                "requiring text generation."
            ),
        }
        if platform == "twitter":
            action_criteria["repost"] = (
                "Repost an existing post without adding text."
            )
        else:
            action_criteria["dislike_post"] = (
                "Downvote/dislike an existing post."
            )

        target_criteria = {
            post["key"]: {
                "author": post["author"],
                "content": post["content"],
            }
            for post in posts
        }
        target_criteria["none"] = (
            "No existing post should be targeted."
        )

        try:
            from typesafe_sdk import Choice

            response = await client.system_one(
                state=self._state(agent, platform, posts),
                questions={
                    "action": Choice(
                        instructions=(
                            "What kind of action would this persona "
                            "take right now?"
                        ),
                        criteria=action_criteria,
                    ),
                    "target": Choice(
                        instructions=(
                            "Which feed post best matches the action, "
                            "if an existing post is needed?"
                        ),
                        criteria=target_criteria,
                    ),
                },
            )
            self.stats["jev_calls"] += 1
            self.stats["jev_plans"] += 1
            action_answer = response.choices["action"]
            target_answer = response.choices["target"]
        except Exception as exc:
            self.stats["errors"] += 1
            print(
                f"[JevFish] Jev decision failed for agent {aid}: {exc}"
            )
            if self.mode == "jev":
                return self._manual_action(
                    self.legacy.ActionType.DO_NOTHING,
                    {},
                )
            return self._llm_action()

        if float(action_answer.confidence) < self.threshold:
            return self._llm_action()

        action = self._sample_choice(
            action_answer,
            stochastic=self.sample_probabilities,
        )
        self._record_selected(action)

        if action == "generate":
            return self._llm_action(escalated=True)
        if action == "do_nothing":
            return self._manual_action(
                self.legacy.ActionType.DO_NOTHING,
                {},
            )

        if float(target_answer.confidence) < self.threshold:
            return self._llm_action()

        target_key = self._sample_choice(
            target_answer,
            stochastic=self.sample_probabilities,
        )
        target = next(
            (post for post in posts if post["key"] == target_key),
            None,
        )
        if not target:
            return self._llm_action()

        if action == "like_post":
            return self._manual_action(
                self.legacy.ActionType.LIKE_POST,
                {"post_id": target["post_id"]},
            )
        if action == "repost" and platform == "twitter":
            return self._manual_action(
                self.legacy.ActionType.REPOST,
                {"post_id": target["post_id"]},
            )
        if action == "dislike_post" and platform == "reddit":
            return self._manual_action(
                self.legacy.ActionType.DISLIKE_POST,
                {"post_id": target["post_id"]},
            )
        if (
            action == "follow_author"
            and target.get("author_user_id") is not None
        ):
            return self._manual_action(
                self.legacy.ActionType.FOLLOW,
                {"followee_id": target["author_user_id"]},
            )

        return self._llm_action()

    def _multi_questions(
        self,
        Choice: Any,
        *,
        platform: str,
        posts: list[dict[str, Any]],
    ) -> Dict[str, Any]:
        questions: Dict[str, Any] = {}

        if hasattr(self.legacy.ActionType, "REFRESH"):
            questions["refresh"] = self._binary_choice(
                Choice,
                instruction=(
                    "Would this persona intentionally refresh/check "
                    "their timeline right now?"
                ),
                yes=(
                    "Yes, checking for new content is a natural action "
                    "for this persona at this moment."
                ),
                no=(
                    "No, there is no particular reason to refresh the "
                    "timeline now."
                ),
            )

        if posts:
            questions["like"] = self._binary_choice(
                Choice,
                instruction=(
                    "Would this persona like any visible post right now?"
                ),
                yes=(
                    "Yes, at least one visible post naturally deserves "
                    "a positive reaction from this persona."
                ),
                no=(
                    "No, this persona would not like any visible post "
                    "right now."
                ),
            )
            questions["like_target"] = self._target_choice(
                Choice,
                instruction=(
                    "If liking, which single post is the most natural "
                    "target?"
                ),
                posts=posts,
            )
            questions["follow"] = self._binary_choice(
                Choice,
                instruction=(
                    "Would this persona follow the author of any visible "
                    "post right now?"
                ),
                yes=(
                    "Yes, one author is sufficiently relevant that this "
                    "persona would want to see more from them."
                ),
                no=(
                    "No, this persona would not follow a new author from "
                    "this feed."
                ),
            )
            questions["follow_target"] = self._target_choice(
                Choice,
                instruction=(
                    "If following, which post's author is the most "
                    "natural person to follow?"
                ),
                posts=posts,
            )

            if platform == "twitter":
                questions["repost"] = self._binary_choice(
                    Choice,
                    instruction=(
                        "Would this persona repost any visible post "
                        "without adding text?"
                    ),
                    yes=(
                        "Yes, one post is worth sharing as-is with this "
                        "persona's audience."
                    ),
                    no=(
                        "No, this persona would not repost anything in "
                        "the current feed."
                    ),
                )
                questions["repost_target"] = self._target_choice(
                    Choice,
                    instruction=(
                        "If reposting, which post is the most natural "
                        "target?"
                    ),
                    posts=posts,
                )
                if hasattr(self.legacy.ActionType, "QUOTE_POST"):
                    questions["quote"] = self._binary_choice(
                        Choice,
                        instruction=(
                            "Would this persona quote a visible post "
                            "with original commentary?"
                        ),
                        yes=(
                            "Yes, this persona has something specific "
                            "and worthwhile to add to one post."
                        ),
                        no=(
                            "No, this persona would not add commentary "
                            "to a visible post now."
                        ),
                    )
                    questions["quote_target"] = self._target_choice(
                        Choice,
                        instruction=(
                            "If quote-posting, which post should receive "
                            "the commentary?"
                        ),
                        posts=posts,
                    )
            else:
                questions["dislike"] = self._binary_choice(
                    Choice,
                    instruction=(
                        "Would this persona downvote/dislike any visible "
                        "post right now?"
                    ),
                    yes=(
                        "Yes, one visible post deserves a negative "
                        "reaction from this persona."
                    ),
                    no=(
                        "No, this persona would not downvote anything "
                        "in the current feed."
                    ),
                )
                questions["dislike_target"] = self._target_choice(
                    Choice,
                    instruction=(
                        "If disliking, which single post is the most "
                        "natural target?"
                    ),
                    posts=posts,
                )
                if hasattr(self.legacy.ActionType, "CREATE_COMMENT"):
                    questions["comment"] = self._binary_choice(
                        Choice,
                        instruction=(
                            "Would this persona write a comment on a "
                            "visible post?"
                        ),
                        yes=(
                            "Yes, this persona has a concrete response "
                            "worth writing to one post."
                        ),
                        no=(
                            "No, this persona would not write a comment "
                            "right now."
                        ),
                    )
                    questions["comment_target"] = self._target_choice(
                        Choice,
                        instruction=(
                            "If commenting, which post is the natural "
                            "target?"
                        ),
                        posts=posts,
                    )

        if hasattr(self.legacy.ActionType, "CREATE_POST"):
            questions["create_post"] = self._binary_choice(
                Choice,
                instruction=(
                    "Would this persona create an original standalone "
                    "post right now?"
                ),
                yes=(
                    "Yes, this persona has something sufficiently "
                    "specific and relevant to say publicly now."
                ),
                no=(
                    "No, this persona would not create an original post "
                    "at this moment."
                ),
            )

        return questions

    def _selected_gate(
        self,
        response: Any,
        name: str,
    ) -> tuple[bool, float, bool]:
        """Return (selected, confidence, uncertain_yes)."""
        answer = response.choices.get(name)
        if answer is None:
            return False, 0.0, False
        choice, confidence = self._choose(answer)
        if choice != "yes":
            return False, confidence, False
        if confidence < self.threshold:
            self.stats["uncertain_gates"] += 1
            return False, confidence, True
        return True, confidence, False

    def _candidate_with_target(
        self,
        response: Any,
        gate_name: str,
        target_name: str,
        posts: list[dict[str, Any]],
    ) -> tuple[Optional[dict[str, Any]], bool]:
        selected, gate_confidence, uncertain = self._selected_gate(
            response,
            gate_name,
        )
        if not selected:
            return None, uncertain

        target_answer = response.choices.get(target_name)
        if target_answer is None:
            return None, True

        target, target_confidence = self._target_from_answer(
            target_answer,
            posts,
        )
        if target is None or target_confidence < self.threshold:
            self.stats["uncertain_gates"] += 1
            return None, True

        return {
            "name": gate_name,
            "score": min(gate_confidence, target_confidence),
            "target": target,
        }, uncertain

    async def _generate_text(
        self,
        *,
        kind: str,
        agent: Any,
        platform: str,
        posts: list[dict[str, Any]],
        target: Optional[dict[str, Any]] = None,
    ) -> Optional[str]:
        client = await self._ensure_llm_client()
        if client is None:
            return None

        persona = json.dumps(
            self._persona(agent),
            ensure_ascii=False,
        )
        recent_feed = json.dumps(
            [
                {
                    "author": post["author"],
                    "content": post["content"],
                }
                for post in posts[:6]
            ],
            ensure_ascii=False,
        )

        if kind == "create_post":
            task = (
                "Write one plausible standalone social-media post this "
                "person would publish now."
            )
        elif kind == "quote":
            task = (
                "Write only the short commentary this person would add "
                "while quote-posting the target."
            )
        else:
            task = (
                "Write only the comment this person would leave on the "
                "target post."
            )

        target_text = ""
        if target is not None:
            target_text = (
                "\nTarget post:\n"
                f"author={target['author']}\n"
                f"content={target['content']}"
            )

        prompt = (
            f"Platform: {platform}\n"
            f"Persona: {persona}\n"
            f"Recent feed: {recent_feed}"
            f"{target_text}\n\n"
            f"{task}\n"
            "Preserve the persona. Be natural, concise, and specific. "
            "Do not explain your answer or wrap it in quotes. Avoid "
            "generic AI-style enthusiasm. Use hashtags only if this "
            "persona would naturally use them."
        )

        kwargs: Dict[str, Any] = {
            "model": self.llm_model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You materialize a simulated person's already-"
                        "chosen social action into natural language. "
                        "Output only the requested social text."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            "max_tokens": 256,
            "temperature": 0.7,
        }
        if self.llm_base_url and "openrouter.ai" in self.llm_base_url:
            kwargs["extra_body"] = {
                "reasoning": {"effort": "low"}
            }

        try:
            response = await client.chat.completions.create(**kwargs)
            text = (
                response.choices[0].message.content or ""
            ).strip()
            if not text:
                raise RuntimeError("System-Two returned empty text")
            self.stats["system_two_calls"] += 1
            bucket = self.stats["system_two_by_type"]
            bucket[kind] = int(bucket.get(kind, 0)) + 1
            return text[:1200]
        except Exception as exc:
            self.stats["system_two_errors"] += 1
            print(
                f"[JevFish] System-Two generation failed "
                f"for {kind}: {exc}"
            )
            return None

    async def _materialize_candidate(
        self,
        candidate: dict[str, Any],
        *,
        agent: Any,
        platform: str,
        posts: list[dict[str, Any]],
    ) -> Optional[Any]:
        name = candidate["name"]
        target = candidate.get("target")
        self._record_selected(name)

        if name == "refresh":
            return self._manual_action(
                self.legacy.ActionType.REFRESH,
                {},
            )
        if name == "like" and target is not None:
            return self._manual_action(
                self.legacy.ActionType.LIKE_POST,
                {"post_id": target["post_id"]},
            )
        if name == "repost" and target is not None:
            return self._manual_action(
                self.legacy.ActionType.REPOST,
                {"post_id": target["post_id"]},
            )
        if name == "dislike" and target is not None:
            return self._manual_action(
                self.legacy.ActionType.DISLIKE_POST,
                {"post_id": target["post_id"]},
            )
        if (
            name == "follow"
            and target is not None
            and target.get("author_user_id") is not None
        ):
            return self._manual_action(
                self.legacy.ActionType.FOLLOW,
                {"followee_id": target["author_user_id"]},
            )

        if name in {"create_post", "quote", "comment"}:
            if self.mode == "jev":
                self.stats["generative_skipped"] += 1
                return None

            text = await self._generate_text(
                kind=name,
                agent=agent,
                platform=platform,
                posts=posts,
                target=target,
            )
            if not text:
                return None

            if name == "create_post":
                return self._manual_action(
                    self.legacy.ActionType.CREATE_POST,
                    {"content": text},
                )
            if name == "quote" and target is not None:
                return self._manual_action(
                    self.legacy.ActionType.QUOTE_POST,
                    {
                        "post_id": target["post_id"],
                        "quote_content": text,
                    },
                )
            if name == "comment" and target is not None:
                return self._manual_action(
                    self.legacy.ActionType.CREATE_COMMENT,
                    {
                        "post_id": target["post_id"],
                        "content": text,
                    },
                )

        return None

    async def decide_bundle(
        self,
        agent: Any,
        *,
        db_path: str,
        platform: str,
    ) -> Any:
        """V0.2 policy: one Jev call -> sparse multi-action OASIS bundle."""
        if self.mode == "llm":
            return self._llm_action()

        client = await self._ensure_client()
        if client is None:
            return self._llm_action()

        aid = _agent_id(agent)
        posts = self._recent_posts(db_path, aid)

        try:
            from typesafe_sdk import Choice

            questions = self._multi_questions(
                Choice,
                platform=platform,
                posts=posts,
            )
            if not questions:
                if self.mode == "jev":
                    return self._manual_action(
                        self.legacy.ActionType.DO_NOTHING,
                        {},
                    )
                return self._llm_action()

            response = await client.system_one(
                state=self._state(agent, platform, posts),
                questions=questions,
            )
            self.stats["jev_calls"] += 1
            self.stats["jev_plans"] += 1
        except Exception as exc:
            self.stats["errors"] += 1
            print(
                f"[JevFish] Jev multi-action decision failed "
                f"for agent {aid}: {exc}"
            )
            if self.mode == "jev":
                return self._manual_action(
                    self.legacy.ActionType.DO_NOTHING,
                    {},
                )
            return self._llm_action()

        candidates: list[dict[str, Any]] = []
        saw_uncertainty = False

        if "refresh" in response.choices:
            selected, confidence, uncertain = self._selected_gate(
                response,
                "refresh",
            )
            saw_uncertainty = saw_uncertainty or uncertain
            if selected:
                candidates.append(
                    {
                        "name": "refresh",
                        "score": confidence,
                    }
                )

        target_specs = [
            ("like", "like_target"),
            ("follow", "follow_target"),
        ]
        if platform == "twitter":
            target_specs.append(("repost", "repost_target"))
            if "quote" in response.choices:
                target_specs.append(("quote", "quote_target"))
        else:
            target_specs.append(("dislike", "dislike_target"))
            if "comment" in response.choices:
                target_specs.append(("comment", "comment_target"))

        for gate_name, target_name in target_specs:
            if gate_name not in response.choices:
                continue
            candidate, uncertain = self._candidate_with_target(
                response,
                gate_name,
                target_name,
                posts,
            )
            saw_uncertainty = saw_uncertainty or uncertain
            if candidate is not None:
                candidates.append(candidate)

        if "create_post" in response.choices:
            selected, confidence, uncertain = self._selected_gate(
                response,
                "create_post",
            )
            saw_uncertainty = saw_uncertainty or uncertain
            if selected:
                candidates.append(
                    {
                        "name": "create_post",
                        "score": confidence,
                    }
                )

        candidates.sort(
            key=lambda item: float(item.get("score", 0.0)),
            reverse=True,
        )
        candidates = candidates[: self.max_actions]

        if not candidates:
            if saw_uncertainty and self.mode == "hybrid":
                return self._llm_action(escalated=True)
            self._record_selected("do_nothing")
            return self._manual_action(
                self.legacy.ActionType.DO_NOTHING,
                {},
            )

        generative_used = 0
        actions: list[Any] = []
        needs_unrestricted_llm = False

        for candidate in candidates:
            is_generative = candidate["name"] in {
                "create_post",
                "quote",
                "comment",
            }
            if (
                is_generative
                and generative_used >= self.max_system_two_actions
            ):
                continue
            if is_generative:
                generative_used += 1

            materialized = await self._materialize_candidate(
                candidate,
                agent=agent,
                platform=platform,
                posts=posts,
            )
            if materialized is not None:
                actions.append(materialized)
            elif is_generative and self.mode == "hybrid":
                needs_unrestricted_llm = True

        if needs_unrestricted_llm:
            actions.append(self._llm_action(escalated=True))

        if not actions:
            if saw_uncertainty and self.mode == "hybrid":
                return self._llm_action(escalated=True)
            self._record_selected("do_nothing")
            return self._manual_action(
                self.legacy.ActionType.DO_NOTHING,
                {},
            )

        if len(actions) > 1:
            self.stats["multi_action_agents"] += 1
        return actions

    async def transform_actions(
        self,
        actions: Mapping[Any, Any],
        *,
        db_path: str,
        platform: str,
    ) -> Dict[Any, Any]:
        """Replace bare OASIS LLMAction values; preserve explicit seed/manual actions."""
        transformed: Dict[Any, Any] = {}
        pending: list[tuple[Any, Any]] = []

        for agent, action in actions.items():
            if isinstance(action, self.legacy.LLMAction):
                pending.append((agent, action))
            else:
                transformed[agent] = action
                self.stats["passthrough_actions"] += 1

        if pending:
            policy = (
                self.decide_bundle
                if self.policy_mode == "multi"
                else self.decide
            )
            decisions = await asyncio.gather(
                *(
                    policy(
                        agent,
                        db_path=db_path,
                        platform=platform,
                    )
                    for agent, _ in pending
                )
            )
            for (agent, _), decision in zip(
                pending,
                decisions,
            ):
                transformed[agent] = decision

        return transformed

    async def close(self) -> None:
        if self._client is not None:
            await self._client.aclose()
            self._client = None
        if self._llm_client is not None:
            await self._llm_client.close()
            self._llm_client = None


class JevEnvironmentProxy:
    def __init__(
        self,
        env: Any,
        engine: JevDecisionEngine,
        *,
        db_path: str,
        platform: str,
    ) -> None:
        object.__setattr__(self, "_env", env)
        object.__setattr__(self, "_engine", engine)
        object.__setattr__(self, "_db_path", db_path)
        object.__setattr__(self, "_platform", platform)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._env, name)

    def __setattr__(self, name: str, value: Any) -> None:
        if name.startswith("_"):
            object.__setattr__(self, name, value)
        else:
            setattr(self._env, name, value)

    async def step(
        self,
        actions: Mapping[Any, Any],
    ) -> Any:
        transformed = await self._engine.transform_actions(
            actions,
            db_path=self._db_path,
            platform=self._platform,
        )
        return await self._env.step(transformed)

    async def close(self) -> Any:
        self._write_metrics()
        await self._engine.close()
        return await self._env.close()

    def _write_metrics(self) -> None:
        try:
            path = (
                Path(self._db_path).parent
                / f"jevfish_{self._platform}_metrics.json"
            )
            payload = dict(self._engine.stats)
            payload["platform"] = self._platform
            payload["database"] = self._db_path
            path.write_text(
                json.dumps(
                    payload,
                    indent=2,
                    ensure_ascii=False,
                ),
                encoding="utf-8",
            )
        except Exception as exc:
            print(f"[JevFish] unable to write metrics: {exc}")


def install_jevfish(
    legacy_module: Any,
) -> JevDecisionEngine:
    """Patch an imported simulator so newly-created OASIS envs are proxied."""
    config = _load_config_from_argv()
    engine = JevDecisionEngine(legacy_module, config)
    original_make = legacy_module.oasis.make

    def make_with_jev(
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        env = original_make(*args, **kwargs)
        db_path = str(kwargs.get("database_path") or "")
        platform = _platform_name(kwargs.get("platform"))
        return JevEnvironmentProxy(
            env,
            engine,
            db_path=db_path,
            platform=platform,
        )

    legacy_module.oasis.make = make_with_jev
    print(
        "[JevFish] decision engine="
        f"{engine.mode}, policy={engine.policy_mode}, "
        f"model={engine.model}, threshold={engine.threshold:.2f}, "
        f"sampling={'on' if engine.sample_probabilities else 'off'}, "
        f"max_actions={engine.max_actions}"
    )
    return engine
